# data
data_dir: 'G:\SemesterProject\GSC\dataset' # win
data_url: 'https://storage.googleapis.com/download.tensorflow.org/data/speech_commands_v0.02.tar.gz'
noise_dir: 'G:\SemesterProject\DEMAND\dataset' # win
# hyperparameters
epochs: 1
batch_size: 128
silence_percentage: 10.0
unknown_percentage: 10.0
validation_percentage: 10.0
testing_percentage: 10.0
background_frequency: 1
background_volume: 5
