# data
# data_dir: 'G:\SemesterProject\GSC\dataset' # win
data_dir: '/usr/scratch/sassauna2/sem24f39/GSC/dataset' # linux
data_url: 'https://storage.googleapis.com/download.tensorflow.org/data/speech_commands_v0.02.tar.gz'
# noise_dir: 'G:\SemesterProject\DEMAND\dataset' # win
noise_dir: '/usr/scratch/sassauna2/sem24f39/DEMAND/dataset_48k' # linux
noise_dataset: 'demand'
volume_ratio: 1 # lower means noise volume is higher
# hyperparameters
epochs: 200 # pretraining epochs
epochs_CL: 16 # Continual Learning epochs
n_classes: 35
batch_size: 128
patience: 10
kd_alpha: 1
# data processing
new_data_ratio: 0.5
snr: -8 # dB
n_batches_dil: 110
silence_percentage: 10.0
unknown_percentage: 10.0
validation_percentage: 10.0
testing_percentage: 10.0
background_frequency: 1
background_volume: 1
memory_buffer_size: 1024
new_data_ratio: 0.5
n_clusters: 10
alpha: 0.5
# seed: 59185
seed: 5
# wandb
project_name: 'KWS'

